
name: Java CI with Maven

on:
  push:
    branches: [ "main" ] 

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package --file pom.xml
  
  Fs-Scan:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: target/*.jar

      - name: FS scan
        run: |
          trivy fs --format table -o report-table.html .

  Sonar-scan-Quality-gate:
    runs-on: self-hosted
    needs: [Fs-Scan] 
    steps:
      - name:  SonarQube Scan
        uses:  sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
  docker:
    runs-on: self-hosted
    needs: Sonar-scan-Quality-gate
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build the image
        run: |
           docker build -t ${{secrets.DOCKERHUB_USERNAME}}/boardgame:${{github.sha}} .  
            docker tag spencerxxxwb/boardgame:${{ github.sha }} spencerxxxwb/boardgame:latest
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Trivy Image Scan
        run: |
          trivy image --format table -o trivy-image-report.html ${{secrets.DOCKERHUB_USERNAME}}/boardgame:${{github.sha}}

      - name: push docker image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/boardgame:lastest
      
  deploy-to-k8:
    needs: docker
    runs-on: self-hosted
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-west-2 --name my-cluster

      - name: Replace Image Tag in Manifest
        run: |
          sed -i 's|IMAGE_PLACEHOLDER|${{ secrets.DOCKERHUB_USERNAME }}/boardgame:${{ github.sha }}|g' deployment-service.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment-service.yaml -n webapps
          kubectl get pods -n webapps

          
